project:
  type: website
  output-dir: docs

website:
  title: "Dexterous Microrobotics Lab"
  favicon: images/logo2.png
  navbar:
    logo: images/logo2.png
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publication.qmd
        text: Publications
      - href: team.qmd
        text: Team
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true